export const REDIS_CLIENT = 'REDIS_CLIENT';
export const REDIS_HOST = 'REDIS_HOST';
export const REDIS_PORT = 'REDIS_PORT';
export const REDIS_PASSWORD = 'REDIS_PASSWORD';
export const REDIS_COASTER_STREAM_KEY = 'COASTER_EVENTS';
export const REDIS_COASTER_GROUP_NAME = 'COASTER_GROUP';
export const REDIS_COASTER_EVENT_NAME = 'COASTER';
export const REDIS_NODE = `node-${Math.random().toString(36).substring(2, 8)}`;
export const REDIS_STREAM_FALLBACK_FILE = 'redis-stream-fallback.json';
